### PR TITLE
Initial CMake build scripts

### PR DESCRIPTION
**Pull request by dbr**
These nodes look really useful - have been meaning to write something similar for ages but never got around to actually starting, so this is great!

Shoved together a quick CMake based build script, primarily so I can more easily test these at work soon, but.. they should also work on both Linux, macOS, and, in theory, maybe even Windows.

They are somewhat WIP; only lightly tested (only verified it produces a sane looking .dylib file on macOS, shall test properly hopefully sometime this week), and the DeepCPNoise node is commented as I didn't into the FastNoise at all (may be worth vendoring it into this repo for simplicity?)

### CODE REVIEW

**Comment by charlesangus** [comment]
Hey, thanks so much for contributing! 

I'll take a look at this soon.

Re: FastNoise dependency, yes. Definitely needs to be included in a more sane fashion into this repo. Probably will commit my FastNoise as a submodule of this repo, so the build scripts can make the FastNoise.a library on demand.

**Comment by charlesangus** [comment]
If you don't mind taking another look at this, I've included the FastNoise library as a submodule. Should build out of the box with DeepCPNoise on Linux with my makefile, and shouldn't be too hard to modify the CMake to work with that. Let me know your thoughts on how that's set up, and thanks again for the help.

**Comment by dbr** [comment]
Updated the CMake script - haven't had a chance to properly test these in Nuke yet, briefly tested and realised I forgot to include the wrapper .cpp (fixed), and was briefly confused by #22 - hopefully will have time on Friday to have a proper look!

Regarding the FastNoise bundling - seems to work, although I've found submodules to be a bit clunky to deal with (even just the extra submodule init call after cloning). Given the FastModule file is so small and unlikely to change too often, I'd probably be tempted to just copy the files into the DeepC repo

**Comment by charlesangus** [comment]
> Given the FastModule file is so small and unlikely to change too often, I'd probably be tempted to just copy the files into the DeepC repo

I'm tempted to do the same, but doesn't the module need to be recompiled at least for Windows? I guess the suggestion would be to vendor in both a FastNoise.a (for Mac/Linux, I think it should be ok for both?) and a FastNoise.lib for Windows?

**Comment by charlesangus** [comment]
I'll take a look at this as soon as I get a chance, and see if I can get the CMake script to work on Windows.

**Comment by charlesangus** [comment]
Had a quick look at this last night. First time using cMake, so forgive me if this is a dumb question, but doesn't it need a directive to link the lib you store in Nuke_LIBRARIES? Wouldn't compile on Windows without that and a few other tweaks. Still trying to get DeepCBlink to compile, and test on Linux, then I'll merge my changes into the PR.

This is definitely the way to go for the cross platform build though, thanks for getting the framework setup.

**Comment by charlesangus** [comment]
Hi there, I've merged in Nathan's CMake setup, which seemed a little closer to working out of the box on Linux. I think there were some linking problems with this one.

I'm going to close this pull request, but if you're interested in merging in the Mac-specific stuff you did here, that would be cool! I don't have a Mac dev machine to test on, unfortunately.

**Pull request closed without merging**
